### ISSUE TITLE
How to save test report file under test project directory?

### ISSUE THREAD

**Issue by Mortimer2013** [jsankey/android-junit-report#22]
Now test report file is saved under data directory of target package. Is it possible to save it under test package? I simply changed 
        mTargetContext.openFileOutput(fileName, Context.MODE_WORLD_READABLE);
to
        mTestContext.openFileOutput(fileName, Context.MODE_WORLD_READABLE);
but no files generated.

**Comment by jsankey** [comment]
Hi, In my original testing (some time ago, though AFAIK nothing has changed) this won't work due to permissions.  During the tests the process only has permission to write in the target app's data area.
